version: '2'
services:
  film:
    image: floodplain/film-database:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  customer:
    image: floodplain/customer-database:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  rental:
    image: floodplain/rental-database:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  cdcservice:
    image: floodplain/demo-movie:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_REACTIVE_URL: postgresql://rental:5432/dvdrental
    depends_on:
      - "rental"
    ports:
      - "8084:8080"
  review:
    image: floodplain/demo-mongodb-review:latest
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo1:27017/?replicaSet=dbrs
    depends_on:
      - mongo1
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ./mongodb-replica-set/rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27017:27017
    # links:
    #   - mongo2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]        
  analytics-postgres:
    image: floodplain/analytics-database:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --set redpanda.enable_idempotence=true
    - --set redpanda.enable_transactions=true
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.11.4
    container_name: redpanda-1
    ports:
    - 8080:8081
    - 9092:9092
    - 29092:29092
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - redpanda
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=filminfo
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=redpanda:29092
      - BOOTSTRAP_SERVERS=redpanda:29092
  connect:
    image: debezium/connect:1.8.1.Final
    depends_on: 
      - redpanda
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=redpanda:29092
      - CONFIG_STORAGE_TOPIC=topic-config
      - OFFSET_STORAGE_TOPIC=offset-storage
      - LOG_LEVEL=INFO
      - KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://redpanda:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://redpanda:8081
  jobmanager:
    image: floodplain/flink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: floodplain/flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
  sql-client: 
    image: floodplain/sql-client:latest
    command: bin/sql-client.sh 
    depends_on: 
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
