version: '2'
services:
  film:
    build: film
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  customer:
    build: customer
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  rental:
    build: rental
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword    